'use strict'; // code generated by pbf v3.1.0

// PBLink ========================================

var PBLink = exports.PBLink = {};

PBLink.read = function (pbf, end) {
    return pbf.readFields(PBLink._readField, {Hash: null, Name: "", Tsize: 0}, end);
};
PBLink._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.Hash = pbf.readBytes();
    else if (tag === 2) obj.Name = pbf.readString();
    else if (tag === 3) obj.Tsize = pbf.readVarint();
};
PBLink.write = function (obj, pbf) {
    if (obj.Hash) pbf.writeBytesField(1, obj.Hash);
    if (obj.Name) pbf.writeStringField(2, obj.Name);
    if (obj.Tsize) pbf.writeVarintField(3, obj.Tsize);
};

// PBNode ========================================

var PBNode = exports.PBNode = {};

PBNode.read = function (pbf, end) {
    return pbf.readFields(PBNode._readField, {Links: [], Data: null}, end);
};
PBNode._readField = function (tag, obj, pbf) {
    if (tag === 2) obj.Links.push(PBLink.read(pbf, pbf.readVarint() + pbf.pos));
    else if (tag === 1) obj.Data = pbf.readBytes();
};
PBNode.write = function (obj, pbf) {
    if (obj.Links) for (var i = 0; i < obj.Links.length; i++) pbf.writeMessage(2, PBLink.write, obj.Links[i]);
    if (obj.Data) pbf.writeBytesField(1, obj.Data);
};
